-- Seed the item catalog with the list from the original single-file app.
-- Idempotent: re-running leaves existing rows (and any dashboard edits) alone.

insert into public.inventory_items (category, category_order, name, food_program, sort_order) values
('Fridge & Dairy',1,'Milk',false,1),
('Fridge & Dairy',1,'Fruit',false,2),
('Fridge & Dairy',1,'18 Eggs',false,3),
('Fridge & Dairy',1,'Mozzarella Cheese',false,4),
('Fridge & Dairy',1,'Cream Cheese (whipped)',false,5),
('Fridge & Dairy',1,'Almond Milk',false,6),
('Fridge & Dairy',1,'Soy Milk',true,7),
('Fridge & Dairy',1,'Vitamin Water',false,8),
('Fridge & Dairy',1,'Grape Juice',false,9),
('Bread & Grains',2,'Whole Grain Bread',false,1),
('Bread & Grains',2,'Bagels (1/2 dozen)',false,2),
('Bread & Grains',2,'Pasta',false,3),
('Bread & Grains',2,'Spaghetti',false,4),
('Bread & Grains',2,'White Rice (bags)',false,5),
('Bread & Grains',2,'Quinoa',true,6),
('Canned & Jarred',3,'Tuna (cans)',false,1),
('Canned & Jarred',3,'Mayo',false,2),
('Canned & Jarred',3,'Tomato Sauce - Large Cans',true,3),
('Canned & Jarred',3,'Tomato Sauce - Small Cans',false,4),
('Canned & Jarred',3,'Peanut Butter',true,5),
('Canned & Jarred',3,'Ketchup',true,6),
('Canned & Jarred',3,'Salsa',true,7),
('Breakfast & Cereal',4,'Old Fashioned Oatmeal',false,1),
('Breakfast & Cereal',4,'Instant Oatmeal Packets',true,2),
('Breakfast & Cereal',4,'Rice Crispies',true,3),
('Breakfast & Cereal',4,'Corn Chex',true,4),
('Breakfast & Cereal',4,'Reese''s Puffs',true,5),
('Breakfast & Cereal',4,'Corn Flakes',true,6),
('Snacks',5,'Chips (Snack 1)',false,1),
('Snacks',5,'Rice Cakes / Crackers (Snack 2)',false,2),
('Snacks',5,'Croutons',false,3),
('Snacks',5,'Nish Nosh Crackers',false,4),
('Snacks',5,'Tortilla Chips (bags)',true,5),
('Beverages',6,'Tea',false,1),
('Beverages',6,'Coffee',false,2),
('Baking & Pantry Staples',7,'Salt',false,1),
('Baking & Pantry Staples',7,'Canola Oil',false,2),
('Baking & Pantry Staples',7,'Lemon Juice',false,3),
('Baking & Pantry Staples',7,'Honey',false,4),
('Baking & Pantry Staples',7,'Spices - Large Bottles (closed)',false,5),
('Baking & Pantry Staples',7,'Spices - Small (closed)',false,6),
('Baking & Pantry Staples',7,'Flour (5lb bags)',false,7),
('Baking & Pantry Staples',7,'Sugar (4lb bags)',false,8),
('Baking & Pantry Staples',7,'Brown Sugar (2lb bags)',false,9),
('Baking & Pantry Staples',7,'Baking Powder',false,10),
('Baking & Pantry Staples',7,'Vanilla Extract',false,11),
('Baking & Pantry Staples',7,'Baking Soda',false,12),
('Baking & Pantry Staples',7,'Cocoa',false,13),
('Produce',8,'Romaine Lettuce',false,1),
('Produce',8,'Cucumber',false,2),
('Produce',8,'Tomatoes',false,3),
('Produce',8,'Potatoes',false,4),
('Produce',8,'Sweet Potatoes',false,5),
('Produce',8,'Onions',false,6),
('Disposables & Utensils',9,'Forks',false,1),
('Disposables & Utensils',9,'Knives',false,2),
('Disposables & Utensils',9,'Spoons',false,3),
('Disposables & Utensils',9,'Cups',false,4),
('Disposables & Utensils',9,'Plates',false,5),
('Disposables & Utensils',9,'Bowls',false,6),
('Disposables & Utensils',9,'Napkins',false,7),
('Disposables & Utensils',9,'Ziplock Bags - Sandwich Size',false,8),
('Disposables & Utensils',9,'Ziplock Bags - Gallon Size',false,9),
('Disposables & Utensils',9,'Parchment Paper Rolls',false,10),
('Disposables & Utensils',9,'Foil - Commercial Size',false,11),
('Disposables & Utensils',9,'Foil - Standard Roll',false,12),
('Disposables & Utensils',9,'Garbage Bags',false,13),
('Cleaning',10,'Dish Soap - Large',false,1),
('Cleaning',10,'Dish Soap - Small',false,2),
('Cleaning',10,'Blue Sponges',false,3),
('Cleaning',10,'Yellow Sponges',false,4),
('Cleaning',10,'Detergent',false,5),
('Shabbos Dishware',11,'Shabbos 9" Plates',false,1),
('Shabbos Dishware',11,'Shabbos 7" Plates',false,2),
('Shabbos Dishware',11,'Shabbos 10oz Bowls',false,3),
('Shabbos Dishware',11,'Shabbos Spoons (Clear)',false,4),
('Shabbos Dishware',11,'Shabbos 6" Serving Dip Bowls',false,5),
('Shabbos Dishware',11,'Shabbos Forks (Clear)',false,6),
('Shabbos Dishware',11,'Shabbos Cups (Tumblers)',false,7),
('Shabbos Dishware',11,'Shabbos Napkins',false,8),
('Shabbos Dishware',11,'Table Cloth Roll',false,9)
on conflict (category, name) do nothing;
